#!/usr/bin/env bash
ZPLUG_INSTALL_PATH="$DOTFILES/zsh/zplug"
# Check if zplug is installed
if [[ ! -d "$ZPLUG_INSTALL_PATH" ]]; then
    git clone https://github.com/zplug/zplug "$ZPLUG_INSTALL_PATH"
    source "$ZPLUG_INSTALL_PATH/init.zsh" && zplug update --self
fi

# Essential
source "$ZPLUG_INSTALL_PATH/init.zsh"

zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh", nice:-1

zplug "plugins/git",            from:oh-my-zsh, if:"(( $+commands[git] ))"

zplug "plugins/git-flow-avh",   from:oh-my-zsh, if:"(( $+commands[git] ))"

zplug "$DOTFILES/zsh/themes",   from:local, use:"devbox.zsh-theme"

zplug "StackExchange/blackbox"

zplug "unixorn/git-extra-commands"

zplug "supercrabtree/k"

zplug "rupa/z"

zplug "chrissicool/zsh-256color"

zplug "zsh-users/zsh-syntax-highlighting", nice:10

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
