#!/usr/bin/env sh
# using gpg-agent to handle ssh
SSH_ENV="$HOME/.ssh/env"

start_agent() {
    /usr/bin/ssh-agent | sed '/^echo/d' > "${SSH_ENV}"
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add > /dev/null
}
#
 # Source SSH settings, if applicable
 if [ -f "${SSH_ENV}" ]; then
     . "${SSH_ENV}" > /dev/null
     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
         start_agent;
     }
 else
     start_agent;
 fi
