#!/bin/bash

create_session() {
    local session=${1-work}
    tmux new-session -s "$session" -n irc -d
    tmux send-keys -t "$session" 'weechat' C-m
    tmux new-window -t "$session" -n console
}

if [[ "$TERM" != "screen-256color" ]]; then
    tmux attach-session -t "$USER" || create_session "$USER"
fi
