#!/usr/bin/env bash
ZPLUG_INSTALL_PATH="$HOME/.zplug"

# Check if zplug is installed
if [[ ! -d "$ZPLUG_INSTALL_PATH" ]]; then
    git clone https://github.com/zplug/zplug "$ZPLUG_INSTALL_PATH"
    source "$ZPLUG_INSTALL_PATH/init.zsh" && zplug update --self
fi

# default compdump to zplug
ZSH_COMPDUMP="$ZPLUG_HOME/zcompdump"

# Essential
source "$ZPLUG_INSTALL_PATH/init.zsh"

zplug "zplug/zplug", hook-build:"zplug --self-manage"
zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh", defer:0
zplug "plugins/git",            from:oh-my-zsh, if:"(( $+commands[git] ))"
zplug "plugins/git-flow-avh",   from:oh-my-zsh, if:"(( $+commands[git] ))"
zplug "$DOTFILES/stowable/zsh/themes",   from:local, use:"devbox.zsh-theme", defer:1
zplug "StackExchange/blackbox"
zplug "unixorn/git-extra-commands"
zplug "supercrabtree/k"
zplug "rupa/z",      use:"z.sh"
zplug "chrissicool/zsh-256color"
zplug "zsh-users/zsh-syntax-highlighting", defer:3
zplug "zsh-users/zsh-autosuggestions", defer:3

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
