#!/usr/bin/env zsh

# a more readable ls output
alias ll='ls -AlrthF'

# root shell but with the current users environment
alias rs='sudo -sE'

[[ -x /usr/bin/neomutt ]] && alias mutt=neomutt

alias o=xdg-open
alias open=xdg-open

# copy pastebinit links to clipboard rather than stdout
alias pastebincp="pastebinit | xsel -ib"

# reloading the configuration
alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"

# using rsync to cp files for proper output
if which rsync >/dev/null; then
    alias cp="rsync --progress -avzh"
fi

alias dotfiles='/usr/bin/git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME'

# Include custom aliases
[[ -f ~/.aliases.local ]] && source ~/.aliases.local
