#!/usr/bin/env sh
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# ignore functions not available on the system
zstyle ':completion:*:functions' ignored-patterns '_*'

