#!/usr/bin/env sh
if [[ -d "$HOME/go" ]]; then
    export GOPATH=$HOME/go
    export GOBIN=$GOPATH/bin
    export PATH=$PATH:$GOBIN
fi

if [[ -d "/opt/google-appengine-go" ]]; then
    export PATH=$PATH:/opt/google-appengine-go
fi

# Enable 1.5 experimental vendoring
export GO15VENDOREXPERIMENT=1

# make sure godoc is always running
(godoc -http=:6060 2>/dev/null &)
