#!/usr/bin/env sh
HISTFILE="$HOME/.zsh/zhistory"

HISTSIZE=5000
SAVEHIST="$HISTSIZE"

# zsh sessions wont overwrite the history file but rather append their history
setopt append_history

# Do not enter command lines into the history list if they begin with a blank
setopt hist_ignore_space

# removes older duplicates if found in history
setopt hist_ignore_all_dups

# perform history substitution and reload the line into the editing buffer
setopt hist_verify

# inclode more information about the executed command
setopt extended_history

# enable real-time sharing across terminal sessions
setopt share_history


