#!/bin/bash

# Dependencies:
# imagemagick
# i3lock-color-git
# scrot

IMAGE="$HOME/.config/i3/i3lock.png"

LOCK="$HOME/.config/i3/lock.png"
# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
BLURTYPE="0x4" # 2.90s

scrot $IMAGE

convert $IMAGE \
    -level 0%,100%,0.6 \
    -blur $BLURTYPE \
    -font Liberation-Sans \
    -pointsize 26 \
    -fill white \
    -gravity center \
    -annotate +0+200 'Type password to unlock' - | composite -gravity center $LOCK - $IMAGE

i3lock \
    --textcolor=ffffff00 \
    --insidecolor=ffffff1c \
    --ringcolor=ffffff3e \
    --linecolor=ffffff00 \
    --keyhlcolor=00000080 \
    --ringvercolor=00000000 \
    --insidevercolor=0000001c \
    --ringwrongcolor=00000055 \
    --insidewrongcolor=0000001c  -i $IMAGE

rm $IMAGE
