#!/usr/bin/bash

# startup dropbox
if [[ ! $(pgrep dropbox) && -x dropboxd ]]; then
    dropboxd &
else
    echo "dropbox is running already"
fi

# start screencloud
if [[ -x /usr/bin/screencloud ]]; then
    screencloud &
fi

# start google music client
if [[ -x /usr/bin/google-musicmanager ]]; then
    google-musicmanager &
fi

# start the network manager
if [[ -x /usr/bin/nm-applet ]]; then
    nm-applet &
fi

if [[ -x /usr/bin/blueman-applet ]]; then
    /usr/bin/blueman-applet &
fi

if [[ -x /usr/bin/udiskie ]]; then
    /usr/bin/udiskie &
fi

if [[ -x /usr/bin/stride ]]; then
    /usr/bin/stride &
fi


