#!/usr/bin/bash

# startup dropbox
# start screencloud
if [[ -x /usr/bin/screencloud ]]; then
    screencloud &
fi

if [[ -x /usr/bin/blueman-applet ]]; then
    /usr/bin/blueman-applet &
fi

if [[ -x /usr/bin/redshift-gtk ]]; then
    /usr/bin/redshift-gtk &
fi
